/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WatchlistRouteRouteImport } from './routes/watchlist/route'
import { Route as ThreadsRouteRouteImport } from './routes/threads/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as WatchlistSymbolRouteImport } from './routes/watchlist/$symbol'
import { Route as ThreadsNewRouteImport } from './routes/threads/new'
import { Route as ThreadsIdRouteImport } from './routes/threads/$id'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRouteRoute = WatchlistRouteRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsRouteRoute = ThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WatchlistRouteRoute,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadsRouteRoute,
} as any)
const WatchlistSymbolRoute = WatchlistSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => WatchlistRouteRoute,
} as any)
const ThreadsNewRoute = ThreadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ThreadsRouteRoute,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThreadsRouteRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/threads': typeof ThreadsRouteRouteWithChildren
  '/watchlist': typeof WatchlistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/watchlist/$symbol': typeof WatchlistSymbolRoute
  '/threads/': typeof ThreadsIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/watchlist/$symbol': typeof WatchlistSymbolRoute
  '/threads': typeof ThreadsIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/threads': typeof ThreadsRouteRouteWithChildren
  '/watchlist': typeof WatchlistRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/watchlist/$symbol': typeof WatchlistSymbolRoute
  '/threads/': typeof ThreadsIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/threads'
    | '/watchlist'
    | '/about'
    | '/settings'
    | '/threads/$id'
    | '/threads/new'
    | '/watchlist/$symbol'
    | '/threads/'
    | '/watchlist/'
    | '/api/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/threads/$id'
    | '/threads/new'
    | '/watchlist/$symbol'
    | '/threads'
    | '/watchlist'
    | '/api/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/threads'
    | '/watchlist'
    | '/about'
    | '/settings'
    | '/threads/$id'
    | '/threads/new'
    | '/watchlist/$symbol'
    | '/threads/'
    | '/watchlist/'
    | '/api/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadsRouteRoute: typeof ThreadsRouteRouteWithChildren
  WatchlistRouteRoute: typeof WatchlistRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof WatchlistRouteRoute
    }
    '/threads/': {
      id: '/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof ThreadsRouteRoute
    }
    '/watchlist/$symbol': {
      id: '/watchlist/$symbol'
      path: '/$symbol'
      fullPath: '/watchlist/$symbol'
      preLoaderRoute: typeof WatchlistSymbolRouteImport
      parentRoute: typeof WatchlistRouteRoute
    }
    '/threads/new': {
      id: '/threads/new'
      path: '/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ThreadsNewRouteImport
      parentRoute: typeof ThreadsRouteRoute
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof ThreadsRouteRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ThreadsRouteRouteChildren {
  ThreadsIdRoute: typeof ThreadsIdRoute
  ThreadsNewRoute: typeof ThreadsNewRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

const ThreadsRouteRouteChildren: ThreadsRouteRouteChildren = {
  ThreadsIdRoute: ThreadsIdRoute,
  ThreadsNewRoute: ThreadsNewRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}

const ThreadsRouteRouteWithChildren = ThreadsRouteRoute._addFileChildren(
  ThreadsRouteRouteChildren,
)

interface WatchlistRouteRouteChildren {
  WatchlistSymbolRoute: typeof WatchlistSymbolRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

const WatchlistRouteRouteChildren: WatchlistRouteRouteChildren = {
  WatchlistSymbolRoute: WatchlistSymbolRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}

const WatchlistRouteRouteWithChildren = WatchlistRouteRoute._addFileChildren(
  WatchlistRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadsRouteRoute: ThreadsRouteRouteWithChildren,
  WatchlistRouteRoute: WatchlistRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
