/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as RepositoriesRouteRouteImport } from './routes/repositories/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as RepositoriesRepositoryIdRouteImport } from './routes/repositories/$repositoryId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRouteRoute = RepositoriesRouteRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRouteRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const RepositoriesRepositoryIdRoute =
  RepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => RepositoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repositories': typeof RepositoriesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repositories': typeof RepositoriesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repositories'
    | '/sessions'
    | '/settings'
    | '/repositories/$repositoryId'
    | '/sessions/$sessionId'
    | '/repositories/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/repositories/$repositoryId'
    | '/sessions/$sessionId'
    | '/repositories'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/repositories'
    | '/sessions'
    | '/settings'
    | '/repositories/$repositoryId'
    | '/sessions/$sessionId'
    | '/repositories/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepositoriesRouteRoute: typeof RepositoriesRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRouteRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/repositories/$repositoryId': {
      id: '/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof RepositoriesRepositoryIdRouteImport
      parentRoute: typeof RepositoriesRouteRoute
    }
  }
}

interface RepositoriesRouteRouteChildren {
  RepositoriesRepositoryIdRoute: typeof RepositoriesRepositoryIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

const RepositoriesRouteRouteChildren: RepositoriesRouteRouteChildren = {
  RepositoriesRepositoryIdRoute: RepositoriesRepositoryIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}

const RepositoriesRouteRouteWithChildren =
  RepositoriesRouteRoute._addFileChildren(RepositoriesRouteRouteChildren)

interface SessionsRouteRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepositoriesRouteRoute: RepositoriesRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
