/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as MaintenanceCaseIdRouteImport } from './routes/maintenance.$caseId'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceCaseIdRoute = MaintenanceCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => MaintenanceRoute,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contractors': typeof ContractorsRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/maintenance/$caseId': typeof MaintenanceCaseIdRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contractors': typeof ContractorsRoute
  '/settings': typeof SettingsRoute
  '/maintenance/$caseId': typeof MaintenanceCaseIdRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contractors': typeof ContractorsRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/maintenance/$caseId': typeof MaintenanceCaseIdRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contractors'
    | '/maintenance'
    | '/settings'
    | '/maintenance/$caseId'
    | '/maintenance/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contractors'
    | '/settings'
    | '/maintenance/$caseId'
    | '/maintenance'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/contractors'
    | '/maintenance'
    | '/settings'
    | '/maintenance/$caseId'
    | '/maintenance/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractorsRoute: typeof ContractorsRoute
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/$caseId': {
      id: '/maintenance/$caseId'
      path: '/$caseId'
      fullPath: '/maintenance/$caseId'
      preLoaderRoute: typeof MaintenanceCaseIdRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MaintenanceRouteChildren {
  MaintenanceCaseIdRoute: typeof MaintenanceCaseIdRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceCaseIdRoute: MaintenanceCaseIdRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractorsRoute: ContractorsRoute,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
